section_patterns = [
    {"label": "SECTIONS", "pattern": [{"lower": "career"}, {"lower": "objective"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "work"}, {"lower": "experience"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "work"}, {"lower": "history"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "work"}, {"lower": "experience"}, {"lower": "summary"}, {"TEXT": ":"}]},
    {"label": "SECTIONS", "pattern": [{"lower": "education"}, {"TEXT": ":"}]},
    {"label": "SECTIONS", "pattern": [{"lower": "strengths"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "education"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "experience"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "skills"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "projects"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "interest"}, {'TEXT': {'REGEX': '\n'}}]},

    {"label": "SECTIONS", "pattern": [{"lower": "summary"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "technical"}, {"lower": "skills"}, {"TEXT": ":"}]},
    {"label": "SECTIONS", "pattern": [{"lower": "professional"}, {"lower": "summary"}, {"TEXT": ":"}]},
    {"label": "SECTIONS", "pattern": [{"lower": "professional"}, {"lower": "development"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "projects"}, {"lower": "information"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "educational"}, {"lower": "background"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "academic"}, {"lower": "projects"}, {'TEXT': {'REGEX': '\n'}}]},

    {"label": "SECTIONS",
     "pattern": [{"lower": "roles"}, {"lower": "&"}, {"lower": "responsibilities"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "career"}, {"lower": "objective"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "technical"}, {"lower": "profile"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS", "pattern": [{"lower": "professional"}, {"lower": "skills"}, {'TEXT': {'REGEX': '\n'}}]},
    {"label": "SECTIONS",
     "pattern": [{"lower": "w"}, {"lower": "o"}, {"lower": "r"}, {"lower": "k"}, {"is_space": True}, {"lower": "e"},
                 {"lower": "x"}, {"lower": "p"}, {"lower": "e"}, {"lower": "r"}, {"lower": "i"}, {"lower": "e"},
                 {"lower": "n"}, {"lower": "c"}, {"lower": "e"}]},
    {"label": "SECTIONS",
     "pattern": [{"lower": "e"}, {"lower": "d"}, {"lower": "u"}, {"lower": "c"}, {"lower": "a"}, {"lower": "t"},
                 {"lower": "i"}, {"lower": "o"}, {"lower": "n"}]},
    {"label": "SECTIONS",
     "pattern": [{"lower": "r"}, {"lower": "e"}, {"lower": "f"}, {"lower": "e"}, {"lower": "r"}, {"lower": "e"},
                 {"lower": "n"}, {"lower": "c"}, {"lower": "e"}, {"lower": "s"}]},
    {"label": "SECTIONS",
     "pattern": [{"lower": "s"}, {"lower": "k"}, {"lower": "i"}, {"lower": "l"}, {"lower": "l"}, {"lower": "s"}]},
    {"label": "SECTIONS",
     "pattern": [{"lower": "a"}, {"lower": "b"}, {"lower": "o"}, {"lower": "u"}, {"lower": "t"}, {"is_space": True},
                 {"lower": "m"}, {"lower": "e"}]},
]

patterns = [

    # patterns for ID Card
    {"label": "NIC",
     "pattern": [{"LIKE_NUM": True, "length": 5}, {"TEXT": {"REGEX": "[–-]"}}, {"LIKE_NUM": True, "length": 7},
                 {"TEXT": {"REGEX": "[–-]"}}, {"LIKE_NUM": True, "length": 1}]},
    {"label": "NIC", "pattern": [{"LIKE_NUM": True, "length": 14}]},

    # patterns for email
    {"label": "EMAIL", "pattern": [{"LIKE_EMAIL": True}]},

    # patterns for cellphone
    {"label": "CELL", "pattern": [{"LIKE_NUM": True, "length": 3}, {"IS_PUNCT": True}, {"LIKE_NUM": True, "length": 3},
                                  {"IS_PUNCT": True}, {"LIKE_NUM": True, "length": 7}]},
    {"label": "CELL",
     "pattern": [{"LIKE_NUM": True, "length": 3}, {"LIKE_NUM": True, "length": 3}, {"LIKE_NUM": True, "length": 7}]},
    {"label": "CELL",
     "pattern": [{"LIKE_NUM": True, "length": 4}, {"TEXT": {"REGEX": "[–-]"}}, {"LIKE_NUM": True, "length": 7}]},
    # {"label":"CELL", "pattern":[{"TEXT":{"REGEX":"\+\d+.\d+.\d+"}}]},
    {"label": "CELL", "pattern": [{"TEXT": '('}, {'like_num': True}, {"TEXT": ')'}, {'like_num': True, 'length': 7}]},
    {"label": "LINKS", "pattern": [{"LIKE_URL": True}]},

    # patterns for skills
    {"label": "SKILL", "pattern": [{"lower": "c#.net"}]},
    {"label": "SKILL", "pattern": [{"lower": "java"}]},
    {"label": "SKILL", "pattern": [{"lower": "c++"}]},
    {"label": "SKILL", "pattern": [{"lower": "asp.net"}]},
    {"label": "SKILL", "pattern": [{"lower": "ms"},
                                   {"is_punct": True},
                                   {"lower": "access"}]},
    {"label": "SKILL", "pattern": [{"lower": "ms"}, {"is_punct": True}, {"lower": "office"}]},
    {"label": "SKILL", "pattern": [{"lower": "ms"}, {"is_punct": True}, {"lower": "sql"}]},
    {"label": "SKILL", "pattern": [{"lower": "c++"}]},
    {"label": "SKILL", "pattern": [{"lower": "unity3d"}]},
    {"label": "SKILL", "pattern": [{"lower": "matlab"}]},
    {"label": "SKILL", "pattern": [{"lower": "c#"}]},
    {"label": "SKILL", "pattern": [{"lower": "html"}]},
    {"label": "SKILL", "pattern": [{"lower": "javascript"}]},
    {"label": "SKILL", "pattern": [{"lower": "reactjs"}]},
    {"label": "SKILL", "pattern": [{"lower": "css"}]},
    {"label": "SKILL", "pattern": [{"lower": "php"}]},
    {"label": "SKILL", "pattern": [{"lower": "wordpress"}]},
    {"label": "SKILL", "pattern": [{"lower": "jquery"}]},
    {"label": "SKILL", "pattern": [{"lower": "bootstrap"}]},
    {"label": "SKILL", "pattern": [{"lower": "reactjs"}]},
    {"label": "SKILL", "pattern": [{"lower": "swift"}]},
    {"label": "SKILL", "pattern": [{"lower": "ios"}]},
    {"label": "SKILL", "pattern": [{"lower": "xcode"}]},
    {"label": "SKILL", "pattern": [{"lower": "objective"}, {"is_punct": True}, {"lower": "c"}]},

    {"label": "SKILL", "pattern": [{"lower": "python"}]},
    {"label": "SKILL", "pattern": [{"lower": "django"}]},
    {"label": "SKILL", "pattern": [{"lower": "communication"}]},
    {"label": "SKILL", "pattern": [{"lower": "javascript"}]},
    {"label": "SKILL", "pattern": [{"lower": "react.js"}]},
    {"label": "SKILL", "pattern": [{"lower": "scrapy"}]},
    {"label": "SKILL", "pattern": [{"lower": "djangorestframework"}]},
    {"label": "SKILL", "pattern": [{"lower": "css"}]},
    {"label": "SKILL", "pattern": [{"lower": "git"}]},
    {"label": "SKILL", "pattern": [{"lower": "softwarequalityassurance"}]},
    {"label": "SKILL", "pattern": [{"lower": "leadership"}]},
    {"label": "SKILL", "pattern": [{"lower": "problemsolving"}]},
    {"label": "SKILL", "pattern": [{"lower": "mysql"}]},
    {"label": "SKILL", "pattern": [{"lower": "html"}]},
    {"label": "SKILL", "pattern": [{"lower": "bootstrap"}]},
    {"label": "SKILL", "pattern": [{"lower": "java"}]},
    {"label": "SKILL", "pattern": [{"lower": "jquery"}]},
    {"label": "SKILL", "pattern": [{"lower": "testautomation"}]},
    {"label": "SKILL", "pattern": [{"lower": "android"}]},
    {"label": "SKILL", "pattern": [{"lower": "jira"}]},
    {"label": "SKILL", "pattern": [{"lower": "angularjs"}]},
    {"label": "SKILL", "pattern": [{"lower": "selenium"}]},
    {"label": "SKILL", "pattern": [{"lower": "teamwork"}]},
    {"label": "SKILL", "pattern": [{"lower": "html5"}]},
    {"label": "SKILL", "pattern": [{"lower": "sql"}]},
    {"label": "SKILL", "pattern": [{"lower": "projectmanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "redux"}]},
    {"label": "SKILL", "pattern": [{"lower": "c++"}]},
    {"label": "SKILL", "pattern": [{"lower": "scrum"}]},
    {"label": "SKILL", "pattern": [{"lower": "machinelearning"}]},
    {"label": "SKILL", "pattern": [{"lower": "dataanalysis"}]},
    {"label": "SKILL", "pattern": [{"lower": "php"}]},
    {"label": "SKILL", "pattern": [{"lower": "teammanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "webdevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "blackboxtesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "mongodb"}]},
    {"label": "SKILL", "pattern": [{"lower": "amazonwebservices(aws)"}]},
    {"label": "SKILL", "pattern": [{"lower": "postgresql"}]},
    {"label": "SKILL", "pattern": [{"lower": "unittesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "mobileapptesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "regressiontesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "backbone.js"}]},
    {"label": "SKILL", "pattern": [{"lower": "reactnative"}]},
    {"label": "SKILL", "pattern": [{"lower": "documentation"}]},
    {"label": "SKILL", "pattern": [{"lower": "c#"}]},
    {"label": "SKILL", "pattern": [{"lower": "asp.net"}]},
    {"label": "SKILL", "pattern": [{"lower": "clientrelations"}]},
    {"label": "SKILL", "pattern": [{"lower": "functionaltesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "github"}]},
    {"label": "SKILL", "pattern": [{"lower": "wordpress"}]},
    {"label": "SKILL", "pattern": [{"lower": "iosdevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "sass"}]},
    {"label": "SKILL", "pattern": [{"lower": "photoshop"}]},
    {"label": "SKILL", "pattern": [{"lower": "jenkins"}]},
    {"label": "SKILL", "pattern": [{"lower": "testplanning"}]},
    {"label": "SKILL", "pattern": [{"lower": "bugreporting"}]},
    {"label": "SKILL", "pattern": [{"lower": "uidesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "docker"}]},
    {"label": "SKILL", "pattern": [{"lower": "swift"}]},
    {"label": "SKILL", "pattern": [{"lower": "node.js"}]},
    {"label": "SKILL", "pattern": [{"lower": "regularexpressions"}]},
    {"label": "SKILL", "pattern": [{"lower": "buganalysis"}]},
    {"label": "SKILL", "pattern": [{"lower": "timemanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "dataentry"}]},
    {"label": "SKILL", "pattern": [{"lower": "softwarearchitecture"}]},
    {"label": "SKILL", "pattern": [{"lower": "testdrivendevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "objective-c"}]},
    {"label": "SKILL", "pattern": [{"lower": "deeplearning"}]},
    {"label": "SKILL", "pattern": [{"lower": "testing"}]},
    {"label": "SKILL", "pattern": [{"lower": "qualitycontrol"}]},
    {"label": "SKILL", "pattern": [{"lower": "rubyonrails"}]},
    {"label": "SKILL", "pattern": [{"lower": "github"}]},
    {"label": "SKILL", "pattern": [{"lower": "celery"}]},
    {"label": "SKILL", "pattern": [{"lower": "restfulservices"}]},
    {"label": "SKILL", "pattern": [{"lower": "xpath"}]},
    {"label": "SKILL", "pattern": [{"lower": "testcasedesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "databasedesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "front-enddevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "productmanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "uxdesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "flask"}]},
    {"label": "SKILL", "pattern": [{"lower": "smoketesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "agileprojectmanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "courseauthoring"}]},
    {"label": "SKILL", "pattern": [{"lower": "hibernate"}]},
    {"label": "SKILL", "pattern": [{"lower": "ajax"}]},
    {"label": "SKILL", "pattern": [{"lower": "training"}]},
    {"label": "SKILL", "pattern": [{"lower": "illustrator"}]},
    {"label": "SKILL", "pattern": [{"lower": "backendsupport"}]},
    {"label": "SKILL", "pattern": [{"lower": "bash"}]},
    {"label": "SKILL", "pattern": [{"lower": "es6"}]},
    {"label": "SKILL", "pattern": [{"lower": "testplanexecution"}]},
    {"label": "SKILL", "pattern": [{"lower": "databases"}]},
    {"label": "SKILL", "pattern": [{"lower": "dataprocessing"}]},
    {"label": "SKILL", "pattern": [{"lower": "management"}]},
    {"label": "SKILL", "pattern": [{"lower": "linux"}]},
    {"label": "SKILL", "pattern": [{"lower": "ansible"}]},
    {"label": "SKILL", "pattern": [{"lower": "kanban"}]},
    {"label": "SKILL", "pattern": [{"lower": "mentoring"}]},
    {"label": "SKILL", "pattern": [{"lower": "usabilitytesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "springframework"}]},
    {"label": "SKILL", "pattern": [{"lower": "springmvc"}]},
    {"label": "SKILL", "pattern": [{"lower": "processoptimization"}]},
    {"label": "SKILL", "pattern": [{"lower": "webperformanceoptimization"}]},
    {"label": "SKILL", "pattern": [{"lower": "kotlin"}]},
    {"label": "SKILL", "pattern": [{"lower": "negativetesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "analyticalskills"}]},
    {"label": "SKILL", "pattern": [{"lower": "rabbitmq"}]},
    {"label": "SKILL", "pattern": [{"lower": "scss"}]},
    {"label": "SKILL", "pattern": [{"lower": "performanceandmemoryoptimization"}]},
    {"label": "SKILL", "pattern": [{"lower": "systemtesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "androidappstesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "redis"}]},
    {"label": "SKILL", "pattern": [{"lower": "objectorienteddesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "iosappstesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "c"}]},
    {"label": "SKILL", "pattern": [{"lower": "djangooscar"}]},
    {"label": "SKILL", "pattern": [{"lower": "android/ioswebappstesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "functionalprogramming"}]},
    {"label": "SKILL", "pattern": [{"lower": "mvc"}]},
    {"label": "SKILL", "pattern": [{"lower": "express.js"}]},
    {"label": "SKILL", "pattern": [{"lower": "gulp.js"}]},
    {"label": "SKILL", "pattern": [{"lower": "responsivedesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "sqlservermanagementstudio"}]},
    {"label": "SKILL", "pattern": [{"lower": "pythonunittesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "debugging"}]},
    {"label": "SKILL", "pattern": [{"lower": "nginx"}]},
    {"label": "SKILL", "pattern": [{"lower": "microsoftexcel"}]},
    {"label": "SKILL", "pattern": [{"lower": "json"}]},
    {"label": "SKILL", "pattern": [{"lower": "trello"}]},
    {"label": "SKILL", "pattern": [{"lower": "naturallanguageprocessing"}]},
    {"label": "SKILL", "pattern": [{"lower": "performancetesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "terraform"}]},
    {"label": "SKILL", "pattern": [{"lower": "apitesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "customersupport"}]},
    {"label": "SKILL", "pattern": [{"lower": "webdesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "heroku"}]},
    {"label": "SKILL", "pattern": [{"lower": "linuxsystemadministration"}]},
    {"label": "SKILL", "pattern": [{"lower": "courseqa"}]},
    {"label": "SKILL", "pattern": [{"lower": "graphicdesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "unity3d"}]},
    {"label": "SKILL", "pattern": [{"lower": "j2ee"}]},
    {"label": "SKILL", "pattern": [{"lower": "laravel"}]},
    {"label": "SKILL", "pattern": [{"lower": "sanitytesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "bokchoyautomation"}]},
    {"label": "SKILL", "pattern": [{"lower": "quicklearner"}]},
    {"label": "SKILL", "pattern": [{"lower": "coreldraw"}]},
    {"label": "SKILL", "pattern": [{"lower": "teaching"}]},
    {"label": "SKILL", "pattern": [{"lower": "interiordesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "hadoop"}]},
    {"label": "SKILL", "pattern": [{"lower": "zendesk"}]},
    {"label": "SKILL", "pattern": [{"lower": "materializecss"}]},
    {"label": "SKILL", "pattern": [{"lower": "codeigniter"}]},
    {"label": "SKILL", "pattern": [{"lower": "bigdata"}]},
    {"label": "SKILL", "pattern": [{"lower": "businessdevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "troubleshooting"}]},
    {"label": "SKILL", "pattern": [{"lower": "microsoftword"}]},
    {"label": "SKILL", "pattern": [{"lower": "virtualization"}]},
    {"label": "SKILL", "pattern": [{"lower": "videoediting"}]},
    {"label": "SKILL", "pattern": [{"lower": "emailmarketing"}]},
    {"label": "SKILL", "pattern": [{"lower": "webpack"}]},
    {"label": "SKILL", "pattern": [{"lower": "sdlc"}]},
    {"label": "SKILL", "pattern": [{"lower": "mobileapptesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "acceptancetesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "googleanalytics"}]},
    {"label": "SKILL", "pattern": [{"lower": "operatingsystems"}]},
    {"label": "SKILL", "pattern": [{"lower": "jsx"}]},
    {"label": "SKILL", "pattern": [{"lower": "photography"}]},
    {"label": "SKILL", "pattern": [{"lower": "agileapplicationdevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "entityframework"}]},
    {"label": "SKILL", "pattern": [{"lower": "integrationtesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "underscore.js"}]},
    {"label": "SKILL", "pattern": [{"lower": "designpatterns"}]},
    {"label": "SKILL", "pattern": [{"lower": "domainknowledge"}]},
    {"label": "SKILL", "pattern": [{"lower": "npm"}]},
    {"label": "SKILL", "pattern": [{"lower": "interpersonalskills"}]},
    {"label": "SKILL", "pattern": [{"lower": "jpa"}]},
    {"label": "SKILL", "pattern": [{"lower": "greyboxtesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "edxplatform"}]},
    {"label": "SKILL", "pattern": [{"lower": "webaccessibility"}]},
    {"label": "SKILL", "pattern": [{"lower": "svn"}]},
    {"label": "SKILL", "pattern": [{"lower": "rxjava"}]},
    {"label": "SKILL", "pattern": [{"lower": "leadgeneration"}]},
    {"label": "SKILL", "pattern": [{"lower": "mobiletestautomation"}]},
    {"label": "SKILL", "pattern": [{"lower": "writingskills"}]},
    {"label": "SKILL", "pattern": [{"lower": "mongoose"}]},
    {"label": "SKILL", "pattern": [{"lower": "zurbfoundation"}]},
    {"label": "SKILL", "pattern": [{"lower": "inpage"}]},
    {"label": "SKILL", "pattern": [{"lower": "materialdesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "proctoring"}]},
    {"label": "SKILL", "pattern": [{"lower": "seleniumwithc#(with.net+nunitframework)"}]},
    {"label": "SKILL", "pattern": [{"lower": "contentmarketing"}]},
    {"label": "SKILL", "pattern": [{"lower": "i18n"}]},
    {"label": "SKILL", "pattern": [{"lower": "documentmanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "googleapps"}]},
    {"label": "SKILL", "pattern": [{"lower": "azure"}]},
    {"label": "SKILL", "pattern": [{"lower": "drawing"}]},
    {"label": "SKILL", "pattern": [{"lower": "dynamodb"}]},
    {"label": "SKILL", "pattern": [{"lower": "boundaryvalueanalysis"}]},
    {"label": "SKILL", "pattern": [{"lower": "networking"}]},
    {"label": "SKILL", "pattern": [{"lower": "knockoutjs"}]},
    {"label": "SKILL", "pattern": [{"lower": "englishfluency"}]},
    {"label": "SKILL", "pattern": [{"lower": "newrelic"}]},
    {"label": "SKILL", "pattern": [{"lower": "productdevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "websocket"}]},
    {"label": "SKILL", "pattern": [{"lower": "computervision"}]},
    {"label": "SKILL", "pattern": [{"lower": "datavisualization"}]},
    {"label": "SKILL", "pattern": [{"lower": "pivotaltracker"}]},
    {"label": "SKILL", "pattern": [{"lower": "marketingstrategy"}]},
    {"label": "SKILL", "pattern": [{"lower": "softwaresecurity"}]},
    {"label": "SKILL", "pattern": [{"lower": "haml"}]},
    {"label": "SKILL", "pattern": [{"lower": "cleancodepractices"}]},
    {"label": "SKILL", "pattern": [{"lower": "appium"}]},
    {"label": "SKILL", "pattern": [{"lower": "grievancehandling"}]},
    {"label": "SKILL", "pattern": [{"lower": "comptiaa+"}]},
    {"label": "SKILL", "pattern": [{"lower": "stlc"}]},
    {"label": "SKILL", "pattern": [{"lower": "ubuntu"}]},
    {"label": "SKILL", "pattern": [{"lower": "matlab"}]},
    {"label": "SKILL", "pattern": [{"lower": "internationalizationtesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "empathy"}]},
    {"label": "SKILL", "pattern": [{"lower": "djangoadmin"}]},
    {"label": "SKILL", "pattern": [{"lower": "imagetagging"}]},
    {"label": "SKILL", "pattern": [{"lower": "urdu/arabictyping"}]},
    {"label": "SKILL", "pattern": [{"lower": "tableau"}]},
    {"label": "SKILL", "pattern": [{"lower": "softwaredevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "lodash"}]},
    {"label": "SKILL", "pattern": [{"lower": "3dstudiomax"}]},
    {"label": "SKILL", "pattern": [{"lower": "windowssystemssupport"}]},
    {"label": "SKILL", "pattern": [{"lower": "awsmachinelearning"}]},
    {"label": "SKILL", "pattern": [{"lower": "openstack"}]},
    {"label": "SKILL", "pattern": [{"lower": "analysisandreporting"}]},
    {"label": "SKILL", "pattern": [{"lower": "technicaldocumentation"}]},
    {"label": "SKILL", "pattern": [{"lower": "mailgun"}]},
    {"label": "SKILL", "pattern": [{"lower": "research"}]},
    {"label": "SKILL", "pattern": [{"lower": "refactoring"}]},
    {"label": "SKILL", "pattern": [{"lower": "webstorm"}]},
    {"label": "SKILL", "pattern": [{"lower": "comptianetwork+"}]},
    {"label": "SKILL", "pattern": [{"lower": "salespresentations"}]},
    {"label": "SKILL", "pattern": [{"lower": "wcfservices"}]},
    {"label": "SKILL", "pattern": [{"lower": "conflictmanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "macostroubleshooting"}]},
    {"label": "SKILL", "pattern": [{"lower": "inboundmarketing"}]},
    {"label": "SKILL", "pattern": [{"lower": "yarn"}]},
    {"label": "SKILL", "pattern": [{"lower": "functionalspecifications"}]},
    {"label": "SKILL", "pattern": [{"lower": "redux-saga"}]},
    {"label": "SKILL", "pattern": [{"lower": "shopify"}]},
    {"label": "SKILL", "pattern": [{"lower": "loadtesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "usabilityengineering"}]},
    {"label": "SKILL", "pattern": [{"lower": "digitalmedia"}]},
    {"label": "SKILL", "pattern": [{"lower": "haskell"}]},
    {"label": "SKILL", "pattern": [{"lower": "statistics"}]},
    {"label": "SKILL", "pattern": [{"lower": "stripe"}]},
    {"label": "SKILL", "pattern": [{"lower": "datastructures"}]},
    {"label": "SKILL", "pattern": [{"lower": "cssselector"}]},
    {"label": "SKILL", "pattern": [{"lower": "end-to-endtesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "interviewingskills"}]},
    {"label": "SKILL", "pattern": [{"lower": "sendgrid"}]},
    {"label": "SKILL", "pattern": [{"lower": "logodesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "reportwriting"}]},
    {"label": "SKILL", "pattern": [{"lower": "jasmine"}]},
    {"label": "SKILL", "pattern": [{"lower": "webappsecurity"}]},
    {"label": "SKILL", "pattern": [{"lower": "vscode"}]},
    {"label": "SKILL", "pattern": [{"lower": "interfacetesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "databasetesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "layer7loadbalancing"}]},
    {"label": "SKILL", "pattern": [{"lower": "architecturaldesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "springboot"}]},
    {"label": "SKILL", "pattern": [{"lower": "cinema4d"}]},
    {"label": "SKILL", "pattern": [{"lower": "securitytesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "sqlserveranalysis"}]},
    {"label": "SKILL", "pattern": [{"lower": "kubernetes"}]},
    {"label": "SKILL", "pattern": [{"lower": "crm"}]},
    {"label": "SKILL", "pattern": [{"lower": "go"}]},
    {"label": "SKILL", "pattern": [{"lower": "mariadb"}]},
    {"label": "SKILL", "pattern": [{"lower": "eventmanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "salesforce"}]},
    {"label": "SKILL", "pattern": [{"lower": "socket.io"}]},
    {"label": "SKILL", "pattern": [{"lower": "visualstudio"}]},
    {"label": "SKILL", "pattern": [{"lower": "spark"}]},
    {"label": "SKILL", "pattern": [{"lower": "splunk"}]},
    {"label": "SKILL", "pattern": [{"lower": "typescript"}]},
    {"label": "SKILL", "pattern": [{"lower": "qualityassurance"}]},
    {"label": "SKILL", "pattern": [{"lower": "dagger"}]},
    {"label": "SKILL", "pattern": [{"lower": "tomcat"}]},
    {"label": "SKILL", "pattern": [{"lower": "tourmanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "designthinking"}]},
    {"label": "SKILL", "pattern": [{"lower": "udc"}]},
    {"label": "SKILL", "pattern": [{"lower": "import"}]},
    {"label": "SKILL", "pattern": [{"lower": "fcm"}]},
    {"label": "SKILL", "pattern": [{"lower": "entrepreneurship"}]},
    {"label": "SKILL", "pattern": [{"lower": "wireless"}]},
    {"label": "SKILL", "pattern": [{"lower": "paypalapi"}]},
    {"label": "SKILL", "pattern": [{"lower": "technologyassessment"}]},
    {"label": "SKILL", "pattern": [{"lower": "python-django-backend"}]},
    {"label": "SKILL", "pattern": [{"lower": "googleadwords"}]},
    {"label": "SKILL", "pattern": [{"lower": "userscenarios"}]},
    {"label": "SKILL", "pattern": [{"lower": "mvvm"}]},
    {"label": "SKILL", "pattern": [{"lower": "centos"}]},
    {"label": "SKILL", "pattern": [{"lower": "courseauthoring"}]},
    {"label": "SKILL", "pattern": [{"lower": "softwaredefinednetworks(sdn)"}]},
    {"label": "SKILL", "pattern": [{"lower": "handlebars.js"}]},
    {"label": "SKILL", "pattern": [{"lower": "cypress"}]},
    {"label": "SKILL", "pattern": [{"lower": "graphicfacilitation"}]},
    {"label": "SKILL", "pattern": [{"lower": "servermanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "tfs"}]},
    {"label": "SKILL", "pattern": [{"lower": "grafana"}]},
    {"label": "SKILL", "pattern": [{"lower": "nonfunctionaltesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "presentationskills"}]},
    {"label": "SKILL", "pattern": [{"lower": "flash"}]},
    {"label": "SKILL", "pattern": [{"lower": "workoutput"}]},
    {"label": "SKILL", "pattern": [{"lower": "kibana"}]},
    {"label": "SKILL", "pattern": [{"lower": "jmeter"}]},
    {"label": "SKILL", "pattern": [{"lower": "flutter"}]},
    {"label": "SKILL", "pattern": [{"lower": "systemsanalysis"}]},
    {"label": "SKILL", "pattern": [{"lower": "maven"}]},
    {"label": "SKILL", "pattern": [{"lower": "mezzanine"}]},
    {"label": "SKILL", "pattern": [{"lower": "illustration"}]},
    {"label": "SKILL", "pattern": [{"lower": "macos"}]},
    {"label": "SKILL", "pattern": [{"lower": "yargs"}]},
    {"label": "SKILL", "pattern": [{"lower": "sidekiq"}]},
    {"label": "SKILL", "pattern": [{"lower": "cssselectors"}]},
    {"label": "SKILL", "pattern": [{"lower": "pythonbots"}]},
    {"label": "SKILL", "pattern": [{"lower": "nextgenerationfirewalls"}]},
    {"label": "SKILL", "pattern": [{"lower": "reactelectron"}]},
    {"label": "SKILL", "pattern": [{"lower": "guestposting"}]},
    {"label": "SKILL", "pattern": [{"lower": "twilio"}]},
    {"label": "SKILL", "pattern": [{"lower": "websitestructuredevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "pl/sql"}]},
    {"label": "SKILL", "pattern": [{"lower": "pycharm"}]},
    {"label": "SKILL", "pattern": [{"lower": "slimframework"}]},
    {"label": "SKILL", "pattern": [{"lower": "skillsassessment"}]},
    {"label": "SKILL", "pattern": [{"lower": "phpexcel"}]},
    {"label": "SKILL", "pattern": [{"lower": "airlineticketing"}]},
    {"label": "SKILL", "pattern": [{"lower": "coding"}]},
    {"label": "SKILL", "pattern": [{"lower": "databaseadministration"}]},
    {"label": "SKILL", "pattern": [{"lower": "competitiveanalysis"}]},
    {"label": "SKILL", "pattern": [{"lower": "browserdevelopertools"}]},
    {"label": "SKILL", "pattern": [{"lower": "solr"}]},
    {"label": "SKILL", "pattern": [{"lower": "opencontrail"}]},
    {"label": "SKILL", "pattern": [{"lower": "waterfallmodel"}]},
    {"label": "SKILL", "pattern": [{"lower": "sketch"}]},
    {"label": "SKILL", "pattern": [{"lower": "cocos2d-x"}]},
    {"label": "SKILL", "pattern": [{"lower": "storageareanetwork(san)"}]},
    {"label": "SKILL", "pattern": [{"lower": "360feedback"}]},
    {"label": "SKILL", "pattern": [{"lower": "teststrategy"}]},
    {"label": "SKILL", "pattern": [{"lower": "accessibilitytesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "linkdevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "mobilegames"}]},
    {"label": "SKILL", "pattern": [{"lower": "proxsmtp"}]},
    {"label": "SKILL", "pattern": [{"lower": "opengl"}]},
    {"label": "SKILL", "pattern": [{"lower": "servicedeliverynetworkarchitecture"}]},
    {"label": "SKILL", "pattern": [{"lower": "drupal"}]},
    {"label": "SKILL", "pattern": [{"lower": "xcode"}]},
    {"label": "SKILL", "pattern": [{"lower": "sqlazure"}]},
    {"label": "SKILL", "pattern": [{"lower": "openedxdeployment"}]},
    {"label": "SKILL", "pattern": [{"lower": "increasespeed"}]},
    {"label": "SKILL", "pattern": [{"lower": "devops"}]},
    {"label": "SKILL", "pattern": [{"lower": "andengine(android's2dgamingengine)"}]},
    {"label": "SKILL", "pattern": [{"lower": "hive"}]},
    {"label": "SKILL", "pattern": [{"lower": "stabilitytesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "yelp_data_entry"}]},
    {"label": "SKILL", "pattern": [{"lower": "iis"}]},
    {"label": "SKILL", "pattern": [{"lower": "technicalsupport"}]},
    {"label": "SKILL", "pattern": [{"lower": "organizationaldevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "marketing"}]},
    {"label": "SKILL", "pattern": [{"lower": "contentmanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "informationretrieval&datamining"}]},
    {"label": "SKILL", "pattern": [{"lower": "xml"}]},
    {"label": "SKILL", "pattern": [{"lower": "abilitytoworkunderpressure"}]},
    {"label": "SKILL", "pattern": [{"lower": "electron"}]},
    {"label": "SKILL", "pattern": [{"lower": "quickbooks"}]},
    {"label": "SKILL", "pattern": [{"lower": "ember.js"}]},
    {"label": "SKILL", "pattern": [{"lower": "datatesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "scripting"}]},
    {"label": "SKILL", "pattern": [{"lower": "bugtracking"}]},
    {"label": "SKILL", "pattern": [{"lower": "groovy"}]},
    {"label": "SKILL", "pattern": [{"lower": "cloudformation"}]},
    {"label": "SKILL", "pattern": [{"lower": "intellijidea"}]},
    {"label": "SKILL", "pattern": [{"lower": "googlemaps"}]},
    {"label": "SKILL", "pattern": [{"lower": "oracle"}]},
    {"label": "SKILL", "pattern": [{"lower": "systemprogramming"}]},
    {"label": "SKILL", "pattern": [{"lower": "strategyfacilitation"}]},
    {"label": "SKILL", "pattern": [{"lower": "websiteanalysis"}]},
    {"label": "SKILL", "pattern": [{"lower": "locust"}]},
    {"label": "SKILL", "pattern": [{"lower": "graphql"}]},
    {"label": "SKILL", "pattern": [{"lower": "executivecoaching"}]},
    {"label": "SKILL", "pattern": [{"lower": "chromeextension"}]},
    {"label": "SKILL", "pattern": [{"lower": "splash"}]},
    {"label": "SKILL", "pattern": [{"lower": "gradle"}]},
    {"label": "SKILL", "pattern": [{"lower": ".net"}]},
    {"label": "SKILL", "pattern": [{"lower": "cricket"}]},
    {"label": "SKILL", "pattern": [{"lower": "recordtestprogressandresults"}]},
    {"label": "SKILL", "pattern": [{"lower": "gamedesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "iosdesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "mcsa:windows10"}]},
    {"label": "SKILL", "pattern": [{"lower": "scala"}]},
    {"label": "SKILL", "pattern": [{"lower": "icinga2"}]},
    {"label": "SKILL", "pattern": [{"lower": "iosappsautomation"}]},
    {"label": "SKILL", "pattern": [{"lower": "processimprovement"}]},
    {"label": "SKILL", "pattern": [{"lower": "adobeair"}]},
    {"label": "SKILL", "pattern": [{"lower": "robotium"}]},
    {"label": "SKILL", "pattern": [{"lower": "a11y"}]},
    {"label": "SKILL", "pattern": [{"lower": "concurrencytheory"}]},
    {"label": "SKILL", "pattern": [{"lower": "bicycling"}]},
    {"label": "SKILL", "pattern": [{"lower": "appstoreoptimization"}]},
    {"label": "SKILL", "pattern": [{"lower": "visualbasic"}]},
    {"label": "SKILL", "pattern": [{"lower": "shaders(hlsl/glsl)"}]},
    {"label": "SKILL", "pattern": [{"lower": "concordion"}]},
    {"label": "SKILL", "pattern": [{"lower": "seo(searchengineoptimization)"}]},
    {"label": "SKILL", "pattern": [{"lower": "accountmanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "localseo"}]},
    {"label": "SKILL", "pattern": [{"lower": "visualizationtoolkit"}]},
    {"label": "SKILL", "pattern": [{"lower": "keywordsstrategy"}]},
    {"label": "SKILL", "pattern": [{"lower": "qualitativeresearch"}]},
    {"label": "SKILL", "pattern": [{"lower": "cucumber"}]},
    {"label": "SKILL", "pattern": [{"lower": "blockchain"}]},
    {"label": "SKILL", "pattern": [{"lower": "pytest"}]},
    {"label": "SKILL", "pattern": [{"lower": "androidappsdevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "browserrenderingoptimization"}]},
    {"label": "SKILL", "pattern": [{"lower": "elasticsearch"}]},
    {"label": "SKILL", "pattern": [{"lower": "understandingmobileenvironments"}]},
    {"label": "SKILL", "pattern": [{"lower": "academicwriting"}]},
    {"label": "SKILL", "pattern": [{"lower": "3dmodelling&cad(3dsmax,blender)"}]},
    {"label": "SKILL", "pattern": [{"lower": "coaching"}]},
    {"label": "SKILL", "pattern": [{"lower": "informationsecurityassessment"}]},
    {"label": "SKILL", "pattern": [{"lower": "jta"}]},
    {"label": "SKILL", "pattern": [{"lower": "vue.js"}]},
    {"label": "SKILL", "pattern": [{"lower": "angular"}]},
    {"label": "SKILL", "pattern": [{"lower": "vendormanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "smm(socialmediamarketing)"}]},
    {"label": "SKILL", "pattern": [{"lower": "digitalpainting"}]},
    {"label": "SKILL", "pattern": [{"lower": "dovecot"}]},
    {"label": "SKILL", "pattern": [{"lower": "cross-browserdevelopment"}]},
    {"label": "SKILL", "pattern": [{"lower": "tripscannermanualprocessingreport"}]},
    {"label": "SKILL", "pattern": [{"lower": "socialmediamarketing"}]},
    {"label": "SKILL", "pattern": [{"lower": "thirdpartyapi's(i.egoogle,facebook)"}]},
    {"label": "SKILL", "pattern": [{"lower": "riskandchangemanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "productdesign"}]},
    {"label": "SKILL", "pattern": [{"lower": "firebase"}]},
    {"label": "SKILL", "pattern": [{"lower": "spock"}]},
    {"label": "SKILL", "pattern": [{"lower": "ionicframework"}]},
    {"label": "SKILL", "pattern": [{"lower": "processing"}]},
    {"label": "SKILL", "pattern": [{"lower": "semanticui"}]},
    {"label": "SKILL", "pattern": [{"lower": "apollographql"}]},
    {"label": "SKILL", "pattern": [{"lower": "googlewebmastertools"}]},
    {"label": "SKILL", "pattern": [{"lower": "internetofthings"}]},
    {"label": "SKILL", "pattern": [{"lower": "processengineering"}]},
    {"label": "SKILL", "pattern": [{"lower": "asp.netmvc"}]},
    {"label": "SKILL", "pattern": [{"lower": "adobecreativesuite"}]},
    {"label": "SKILL", "pattern": [{"lower": "posmanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "cloudflare"}]},
    {"label": "SKILL", "pattern": [{"lower": "recruiting"}]},
    {"label": "SKILL", "pattern": [{"lower": "soccer"}]},
    {"label": "SKILL", "pattern": [{"lower": "squash"}]},
    {"label": "SKILL", "pattern": [{"lower": "ldap"}]},
    {"label": "SKILL", "pattern": [{"lower": "automation"}]},
    {"label": "SKILL", "pattern": [{"lower": "websiteaudit"}]},
    {"label": "SKILL", "pattern": [{"lower": "zabbix"}]},
    {"label": "SKILL", "pattern": [{"lower": "marketing&salesautomation"}]},
    {"label": "SKILL", "pattern": [{"lower": "consulting"}]},
    {"label": "SKILL", "pattern": [{"lower": "atom"}]},
    {"label": "SKILL", "pattern": [{"lower": "userresearch"}]},
    {"label": "SKILL", "pattern": [{"lower": "gamemechanics&3dmaths"}]},
    {"label": "SKILL", "pattern": [{"lower": "shellscripting"}]},
    {"label": "SKILL", "pattern": [{"lower": "datacenterarchitecture"}]},
    {"label": "SKILL", "pattern": [{"lower": "groupfacilitation"}]},
    {"label": "SKILL", "pattern": [{"lower": "styledcomponents"}]},
    {"label": "SKILL", "pattern": [{"lower": "googlepenaltyrecovery"}]},
    {"label": "SKILL", "pattern": [{"lower": "embeddedc"}]},
    {"label": "SKILL", "pattern": [{"lower": "crashlytics"}]},
    {"label": "SKILL", "pattern": [{"lower": "elastix,pbx"}]},
    {"label": "SKILL", "pattern": [{"lower": "shiftrostermanagement(weekly,monthly,yearly)"}]},
    {"label": "SKILL", "pattern": [{"lower": "grunt"}]},
    {"label": "SKILL", "pattern": [{"lower": "computergraphics"}]},
    {"label": "SKILL", "pattern": [{"lower": "breachdetectionsystems"}]},
    {"label": "SKILL", "pattern": [{"lower": "proceduralanimations(easingfunctions)"}]},
    {"label": "SKILL", "pattern": [{"lower": "waf"}]},
    {"label": "SKILL", "pattern": [{"lower": "postfix"}]},
    {"label": "SKILL", "pattern": [{"lower": "galeracluster"}]},
    {"label": "SKILL", "pattern": [{"lower": "animationinswift"}]},
    {"label": "SKILL", "pattern": [{"lower": "nagios"}]},
    {"label": "SKILL", "pattern": [{"lower": "ppc"}]},
    {"label": "SKILL", "pattern": [{"lower": "gocd"}]},
    {"label": "SKILL", "pattern": [{"lower": "proceduralmesh/terraingeneration&deformation"}]},
    {"label": "SKILL", "pattern": [{"lower": "influxdb"}]},
    {"label": "SKILL", "pattern": [{"lower": "actionscript"}]},
    {"label": "SKILL", "pattern": [{"lower": "redux-thunk"}]},
    {"label": "SKILL", "pattern": [{"lower": "protractor"}]},
    {"label": "SKILL", "pattern": [{"lower": "flowplayer.js"}]},
    {"label": "SKILL", "pattern": [{"lower": "easeljs"}]},
    {"label": "SKILL", "pattern": [{"lower": "contentdevelopmentstrategy"}]},
    {"label": "SKILL", "pattern": [{"lower": "webservices"}]},
    {"label": "SKILL", "pattern": [{"lower": "atlassianjira"}]},
    {"label": "SKILL", "pattern": [{"lower": "willingnesstolearnnewtechnologies"}]},
    {"label": "SKILL", "pattern": [{"lower": "ruby"}]},
    {"label": "SKILL", "pattern": [{"lower": "html,css,bootsrap"}]},
    {"label": "SKILL", "pattern": [{"lower": "onlinereputationmanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "dataengineering"}]},
    {"label": "SKILL", "pattern": [{"lower": "softwareinstallation"}]},
    {"label": "SKILL", "pattern": [{"lower": "mumps"}]},
    {"label": "SKILL", "pattern": [{"lower": "distributedsystems"}]},
    {"label": "SKILL", "pattern": [{"lower": "mongocompass"}]},
    {"label": "SKILL", "pattern": [{"lower": "customerexperiencemanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "eclipse"}]},
    {"label": "SKILL", "pattern": [{"lower": "rasacore"}]},
    {"label": "SKILL", "pattern": [{"lower": "teambuilding"}]},
    {"label": "SKILL", "pattern": [{"lower": "nunit"}]},
    {"label": "SKILL", "pattern": [{"lower": "designanddecor"}]},
    {"label": "SKILL", "pattern": [{"lower": "freebsd"}]},
    {"label": "SKILL", "pattern": [{"lower": "lightroom"}]},
    {"label": "SKILL", "pattern": [{"lower": "androidsdk"}]},
    {"label": "SKILL", "pattern": [{"lower": "datawarehousing"}]},
    {"label": "SKILL", "pattern": [{"lower": "memes"}]},
    {"label": "SKILL", "pattern": [{"lower": "negotiation"}]},
    {"label": "SKILL", "pattern": [{"lower": "corejava"}]},
    {"label": "SKILL", "pattern": [{"lower": "requirementsanalysis"}]},
    {"label": "SKILL", "pattern": [{"lower": "pentesting"}]},
    {"label": "SKILL", "pattern": [{"lower": "gomatic"}]},
    {"label": "SKILL", "pattern": [{"lower": "googlesheet"}]},
    {"label": "SKILL", "pattern": [{"lower": "jenkinsdsl"}]},
    {"label": "SKILL", "pattern": [{"lower": "sem"}]},
    {"label": "SKILL", "pattern": [{"lower": "jsp"}]},
    {"label": "SKILL", "pattern": [{"lower": "copywriting"}]},
    {"label": "SKILL", "pattern": [{"lower": "xamarin"}]},
    {"label": "SKILL", "pattern": [{"lower": "dax"}]},
    {"label": "SKILL", "pattern": [{"lower": "itsolutions"}]},
    {"label": "SKILL", "pattern": [{"lower": "pfsense"}]},
    {"label": "SKILL", "pattern": [{"lower": "computerhardware"}]},
    {"label": "SKILL", "pattern": [{"lower": "mobileapplications"}]},
    {"label": "SKILL", "pattern": [{"lower": "jms"}]},
    {"label": "SKILL", "pattern": [{"lower": "wpf"}]},
    {"label": "SKILL", "pattern": [{"lower": "react360"}]},
    {"label": "SKILL", "pattern": [{"lower": "flexible"}]},
    {"label": "SKILL", "pattern": [{"lower": "specflow"}]},
    {"label": "SKILL", "pattern": [{"lower": "sqlserverintegrationservices"}]},
    {"label": "SKILL", "pattern": [{"lower": "usecaseanalysis"}]},
    {"label": "SKILL", "pattern": [{"lower": "powerbi"}]},
    {"label": "SKILL", "pattern": [{"lower": "windowstroubleshooting"}]},
    {"label": "SKILL", "pattern": [{"lower": "capistrano"}]},
    {"label": "SKILL", "pattern": [{"lower": "webscraping"}]},
    {"label": "SKILL", "pattern": [{"lower": "marvel(uxprototyping)"}]},
    {"label": "SKILL", "pattern": [{"lower": "wireframes"}]},
    {"label": "SKILL", "pattern": [{"lower": "storemanagement"}]},
    {"label": "SKILL", "pattern": [{"lower": "networksecurity"}]},
    {"label": "SKILL", "pattern": [{"lower": "circleci"}]},
]
